---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 10m
  chart:
    spec:
      chart: velero
      version: 2.30.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    serviceAccount:
      server:
        create: true
        name: velero
    upgradeCRDs: false
    backupsEnabled: true
    snapshotsEnabled: true
    configuration:
      provider: aws
      backupStorageLocation:
        name: minio
        bucket: pvc-backups
        default: true
        config:
          region: minio
          profile: minio
          s3ForcePathStyle: true
          s3Url: http://192.168.15.2:9000
          publicUrl: http://192.168.15.2:9000
    credentials:
      name: minio-creds
      secretContents:
        cloud: |
          [minio]
          aws_access_key_id=${SECRET_HOME_MINIO_ACCESS_KEY}
          aws_secret_access_key=${SECRET_HOME_MINIO_SECRET_KEY}
    schedules:
      daily:
        schedule: "0 5 * * *"
        template:
          ttl: 96h
          storageLocation: minio
          snapshotVolumes: false
          volumeSnapshotLocations:
            - minio
          includedNamespaces:
            - soketi
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.5.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-csi
        image: vsphereveleroplugin/velero-plugin-for-vsphere:1.3.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    kubectl:
      image:
        repository: ghcr.io/k8s-at-home/kubectl
        tag: v1.24.3
    metrics:
      serviceMonitor:
        enabled: false
