---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: velero-crds
  namespace: flux-system
spec:
  interval: 10m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: velero