---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  path: "./manifests/monitoring/kube-prometheus-stack"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-git
