---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/metallb
  - ../base/ingress-nginx
  - ../base/cert-manager
  - ../base/external-dns
patchesStrategicMerge:
  - metallb-values.yaml
  - ingress-nginx-values.yaml
