---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  values:
    configInline:
      address-pools:
        - name: default
          protocol: bgp
          addresses:
            - 103.79.72.8/29
