---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  values:
    configuration:
      backupStorageLocation:
        bucket: rfspager-backups
