---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  interval: 5m
  values:
    configInline:
      peers:
        - peer-address: ${CONFIG_METALLB_PEER_A_ADDRESS}
          peer-asn: 64513
          my-asn: 64514
        - peer-address: ${CONFIG_METALLB_PEER_B_ADDRESS}
          peer-asn: 64513
          my-asn: 64514
