---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-git
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/fluxcd/flux2.git
  ref:
    branch: main
