---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ws
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.soketi.app
      chart: soketi
      version: v0.16.2
      sourceRef:
        kind: HelmRepository
        name: soketi-charts
        namespace: flux-system
      interval: 5m
  values:


    livenessProbe: ""
    readinessProbe: ""

    replicaCount: 5

    serviceMonitor:
      enabled: true

    app:
      image:
        repository: quay.io/soketi/soketi
        pullPolicy: IfNotPresent
        tag: "1.2.0-16-alpine"

      resources:
        requests:
          cpu: 8000m
          memory: 1024Mi
        limits: ""

      mode: full
      command:
        - node
        - /app/bin/server.js
        - start
        - --config=/etc/soketi/soketi-config.json

      extraVolumeMounts:
        - name: config
          mountPath: /etc/soketi/
          readOnly: true

      multicast:
        enabled: false
        hostNetwork: false
        dnsPolicy: ClusterFirstWithHostNet

    ingress:
      enabled: true
      class: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"

      hosts:
        - host: soketi.local
          paths:
            - /

      tls:
        - secretName: soketi-tls
          hosts:
            - soketi.local
    extraVolumes:
        - name: config
          configMap:
            name: soketi-config
