---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: soketi
resources:
  - namespace.yaml
  - redis
  - helm-release.yaml

configMapGenerator:
  - name: soketi-config
    files:
      - soketi-config.json
configurations:
  - kustomizeconfig.yaml
