---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - redis
  - helm-release.yaml
generatorOptions:
  disableNameSuffixHash: true
  disableHash: true
configMapGenerator:
  - name: soketi-config
    namespace: soketi
    files:
      - soketi-config.json5