apiVersion: v1
kind: Secret
metadata:
    name: global-cluster-secrets
    namespace: flux-system
stringData:
    SECRET_GLOBAL_GRAFANA_PASSWORD: ENC[AES256_GCM,data:VqHCqCgOUJ1Tc/T25xQY,iv:v34aAhypsRo+OyYCmpApavThT4pbdub3cyaBOapYrGM=,tag:QdtKEjGb9Y28NkjouDfeCA==,type:str]
    SECRET_GLOBAL_CF_EMAIL: ENC[AES256_GCM,data:Sr74D0kt14OQKePEuCtTicRf,iv:fKMNZGJYvwpIFUWeukYgQyeqzkpHr+LsTmiMz7xsqGI=,tag:XTdls8WwoUQ9rBmN8MuOdw==,type:str]
    SECRET_GLOBAL_CF_API_KEY: ENC[AES256_GCM,data:lhLY2b/tflWghwgFH+3PmsrVaF5K1ovqqf9MohhexcC2urshRQ==,iv:8cfk/sEMrNXohQ1BwOOqeDsWSrv6UkYFFMRKE5FAU8E=,tag:fTppmYosXjn4ElhIdtYSvg==,type:str]
    SECRET_HOME_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Tf/J+f5Za59ecw==,iv:Zmn8p+BFSWTT4GdjifLNpsq96tZR1xNOi6GFtuYz4eM=,tag:7vL3W+sdDj+cq77vrpVfwQ==,type:str]
    SECRET_HOME_MINIO_SECRET_KEY: ENC[AES256_GCM,data:E6c9iWZWxUS/RQ==,iv:gLeWSV/tUxGQCdzfFCkZhQOyalW56Oh7PZl/rebbYHQ=,tag:m/++3B1pUJJKRxHYQ2aKMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-19T12:40:41Z"
    mac: ENC[AES256_GCM,data:uouar798hMoGdwC46GE8XX9qc7lL6ogw4r+I8C+w0K9+dk+GuUUxRw7rquefPVF7P6IKYm0U3flGdnwP7HpP+tg9Ec5WLDQWmVFvL0Tb4yGZgI94NWJacPQJXYTN+iYlCfmmt4o65ZWwaYaHNQTkVJhZftrJSjgtNBhWWuTW4N8=,iv:HDPyIbzlBmjhGTb7BlDxPPSndEUyyrRItR9PREOSocc=,tag:tKaDEaQygaVeB9cucy1JCA==,type:str]
    pgp:
        - created_at: "2022-07-19T12:40:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA94riJsaU78cAQ//XLT7FpGMAJX/r6RkTReK+g1lb+hdFKFC/vCyJkSyxAaK
            feIuUFmQHSQ/n3tS6Y8vQ3G0DMdzKvvFVcWDLg7Kn3ll4/02Pj7l0Tzom55p8D4k
            nHTY4/E2vhQz3rE8zo718GX9gtEvcecL4DAWAxKAWnvSRXv2rufBG+XRrXjk/j9Q
            i3pFTPuopmhnwi5rKsfEjFNfi8iMReozRw0uV4KlV7YOvmTM4en1sAonypF1TZZl
            QeQ7r6wbwkykkGFqK9pn9ldcu5QxgF0A9UOpm+F3F0LkpU2ftMzpcrk7/ZZarBrn
            WkYiKzJVBGkSechLsBmxJRQkwSQx3+p2Xllc6rL9cAwkitv5gbIndQChDwiSWGC7
            wf474L8Y35yuNseqDV1zTdxKf5PX1POmxVztqmd/die1mtog/9YV3ekm9/pegeCh
            V4c4lD84LjwpFOg5ZB0X+aeALX7yZN3WJ+j5W4DzPez7RCf/NnuaYDyupYH9mNgO
            HPgia0XpW6OZY/qamyPXZ/8iVoyf9qSpLncKbqfzOq1lxFUbpAzX9+oceF3xfVSe
            bZtbxAbDAGV43qrVho+dkpABfpDjg74XTZxlSxHfsby+UwGaw2pfCk9XkoDwky0+
            sDC55ikUb19YHftZLz1f9kiosziGlFpd6YuOd1+SBnKZgKOjEldSelQjOkG40jvU
            aAEJAhD5HjJEHVz2Dd1CRrkvVYBQD2Qjbpvx+kEELqDawV9DRNCM4wEPmGu8tUy6
            rMrFtq8O4K4dzBsNrcFKKFHKMyLkZfxeJshIn9ocTbA7aDXFgq6zjcrwHbaq6Oxv
            dZYLp9Tla3bB
            =36mK
            -----END PGP MESSAGE-----
          fp: B42C06716985941889E9BE3C3E7A0C9545A09F8C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
