apiVersion: v1
kind: Secret
metadata:
    name: global-cluster-secrets
    namespace: flux-system
stringData:
    SECRET_GLOBAL_GRAFANA_PASSWORD: ENC[AES256_GCM,data:hfXp77Nn/izliyfzaG9m,iv:RzhbF4u0Rd7SbMXsCZ4ZdTT3QR8NcvNTUuIcorBDH/A=,tag:oIkauJ8APmWjz2COOYPBWA==,type:str]
    SECRET_GLOBAL_CF_EMAIL: ENC[AES256_GCM,data:mzs1icAw++Z6Jo14ou2yYTxa,iv:e062zJEXs2xsBaUBwSQ6d+dLJvoVgLDxgmWcVkYp1kQ=,tag:RYGRxwnw7NNoreEZlps/sg==,type:str]
    SECRET_GLOBAL_CF_API_KEY: ENC[AES256_GCM,data:4LbiIWFVhk+xNI1PJvvyjZ3WcbeDuY2P0u45yVL8zb6IEh9GgQ==,iv:NMCnkrEJrMkoh8gmrVclg21nvHfgpntslWGw9uRoFEg=,tag:txHaYpZpl1wxsFDHFGuBWQ==,type:str]
    SECRET_HOME_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:HZLy1ofFP8AHVQ==,iv:yWKh8uwAmRJyBcePEQWMsgpNTq5OADZl99cVd4T8MD0=,tag:5t1jx2hxoNjz0KPIavcBlw==,type:str]
    SECRET_HOME_MINIO_SECRET_KEY: ENC[AES256_GCM,data:+aBybj9c748O/A==,iv:XjqOehn20Ilbb4fJiPJk8py59WaPMGW9CH6o2qrIoo8=,tag:Tkt2HEh+mcLLnwBspdtzHQ==,type:str]
    SECRET_GLOBAL_MINIO_ROOT_USER: ENC[AES256_GCM,data:4GL7298=,iv:Qf+uMUBmrwGPzg3mZ16Y3TY4gB5006yGU90luIuxmN4=,tag:wUq2BMyupfbz8ZcZuEzfJQ==,type:str]
    SECRET_GLOBAL_MINIO_ROOT_PASS: ENC[AES256_GCM,data:lYCtiyH1ycewxlGRzPIY,iv:5tgZzmkzXr2s1zXQneSs/43iWp1eLXq1Y1DVMQ4T/TY=,tag:9pmANvTyhZ14o4aRx9p5PA==,type:str]
    SECRET_GLOBAL_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:6D2smsPyJmtV76C8tVk+HMll66Zo17/nb8jx,iv:26n9l2Po77CSwgtB35jbuPCm8ZBC+QDKQFHoJIOPgu4=,tag:AckgIh+aw7ddY7C6dvZWAw==,type:str]
    SECRET_GLOBAL_MINIO_SECRET_KEY: ENC[AES256_GCM,data:cwgZPavzH7ataa8lOyzeNKyx4k1bJsNCcQ==,iv:6bu5X6SGdfkjPJCAHbSqBuPmkQ8u48MD3pvtENFJQbQ=,tag:KI75XnVliTQOWCO703lHkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-21T13:16:53Z"
    mac: ENC[AES256_GCM,data:vJsLRHMOYdAl1zBtNXirCF03PYiR8k1T/hC2644iqkf9My+TmKvSWBUikduuwBHk0atjUc1VPWB2cOIKc791lZmHJ/+wGXxkrWAXsJDxtqG9JUsbxLRR6kVyhCC+GyCjxRwU1YU1lOJtLTq9y9SU/0qOQiXW8qnZ8LLM3TlaEkM=,iv:+VsqtCfruwlSXiHX8Tm/UiyPX0IjeH7xqOWG9EXqJfk=,tag:GlmZGHrDEn1JmlZHeceyHg==,type:str]
    pgp:
        - created_at: "2022-07-21T13:16:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA94riJsaU78cARAA4NKYquzKrzv+tcMStD/RiOgHa+XbWw7ihY0xJOhXA18b
            HW+k4m7sxa1zFl5rsBsnC8ym8rBb/pqN02Efy8KQMyrbcERb60V1s/zyEEScxL5Y
            tbe88AqqZG4hz07R76cJO5y1AW2TomdkObB2T2hSjcxWw6cwnIFmyaaiG7HOjtLw
            F2adUgFTrNjUECgZYLCYXCVc2gfQFM0Ng12/cFd0kWUELlc0/6CarVjLgoR4k5JQ
            t+D45NMeXzGetf74l0rlJ/80RBYcY5O0udUISCEXMUOYU9tlvbJbsNMLLwRdiKPW
            k8VaNG7qiQUrk5ZIRPtr+nmCgsSIJ5+pKGIvdAv70WiLoppiwoNvLdR600NqZoHm
            ffVCI0ioYoygm/vX/bOuYoFYAvXLdHG7+onNPyvoeHuxMNB9wFxTYVh0aNg7bZDe
            YyNvwJXZSYwLsZTHCEBEXyLfJz6mpaq9TftIzDtZ2W6TBS3/DscoN0FGnxOFvnID
            s1gN07x3KQUzcwaip3KeWH0tJUOkeArhATIqsFRm8ALn/iVhdgBfJhftUaqF1+d7
            UPwlrANXxkhUNNd1bikXZd5E7G4X9vd6Kphiy0voG1KWcPcyE22XMUYjsySeCR+1
            cKg6+/s8QexJOXgdK6ZV4ccOdTSIIy0+fi+e1u+N5/jk9ludTW/ynGDt7NR4R+jU
            ZgEJAhCd4AnXJEpa1+MUsTLoEk4JC5N7uTD3YHXiAQefRnmfGlA4BwvHBZFQTL2w
            CUvmSyc01G/54Wy+7RbIDovaGjisYw1U05xqW0yNauae06BRmB5VZ9B21+kfWNYv
            pc5WGFkfpA==
            =TdkJ
            -----END PGP MESSAGE-----
          fp: B42C06716985941889E9BE3C3E7A0C9545A09F8C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
