apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rfspager-secrets
    namespace: rfspager
stringData:
    APP_KEY: ENC[AES256_GCM,data:QI/7X7BPupmypjJIYMVF+L3/lI/F3zzW1SOUKWL6d5jnRa5uwedR7ZYbdBuCPUpMPK4q,iv:kq7Vej1bVoX0xAciUk0EFToQ1pRMFvaKzeZUv78wavE=,tag:XjlCAUoEvNlzbQjAqFssWQ==,type:str]
    AWS_ENDPOINT: ENC[AES256_GCM,data:PBw4tisK3ZfXXSuitVSFy+a6mqd9cXy0cOmFQWflezpZQerVQLAxIGV+uGY=,iv:cNPJrZ7uqrVLlD4fAPO9dVAnZInDJQEfVodUxjqKI1k=,tag:WTPGD+zAV43xdnFU9LHaCA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:M9aAPsh3Lno4vLdPXq7pdGAzvobo+/Vmu4WvvlbazQgx,iv:YGFUa0vVbxYNfKaUH23zb+LAF1Lk+20+TGH00J7c2xQ=,tag:Z8BsmURM3kkzBFnI9XgKYg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NhUnaBlDCrIRrd/Id57NuZ0UA6zkA3dcGLFssBVco8k0,iv:A8sQfNDKBlLNY7zqKXynXenpdYUPr/vgrEqxUAvMTN4=,tag:ub8SRWo+iWRBPY2qK6VsCg==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:ErMl6A9wFgfAETHt,iv:Z4VqiBFi1AIejIGE7QNBcdhL2RakybNOhhKar4hcB3s=,tag:NXUsAWS+s3Ny1TFu3TODOg==,type:str]
    AWS_BUCKET: ENC[AES256_GCM,data:pWHLin4DqT8=,iv:GvW5Fm3AIJBqBlmW3fCxZ0AALUVoA6nr5WhSuoH2vA0=,tag:lpb2jOr5LuETP8M3tEtRyA==,type:str]
    AWS_USE_PATH_STYLE_ENDPOINT: ENC[AES256_GCM,data:U+v7+w==,iv:znowrkxV7RwTi+FcRIswRnIvfVXQNsxnMH5G15Yzl9A=,tag:6KESf9lfVUWQx2HFt0lhRw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:4COKBwqCJAGZrdgK9UjBFniTOhXsoAIvBsjrrnBo,iv:E5JLT8hvPK3NfQIW3tKzbL7OSxaL+iMBw0MJE/dWfE8=,tag:7tDiRhSJIvxi5ZT61R+CJA==,type:str]
    PASSPORT_CLIENT_SECRET: ENC[AES256_GCM,data:WG+DttTKG+BMjhOZFytdvvDI5uZYggvuFqXlzmScZ2qWFKYd2tteXQ==,iv:Mzpb2ee6tY3KbbIRMJlbgVMfdo+C0hqj72fNlmOn+9g=,tag:h6YLmrLzL2qHU1iNS47DWg==,type:str]
    REVENUE_CAT_SECRET_KEY: ENC[AES256_GCM,data:yQuOkkwMUQBQuybVovE9AASMX2CapQPtlLv4wQDikAA=,iv:cSRTScURTYy8CvGWOjEewj2hIqFO0TmplI6gIYdne30=,tag:l71ADwzUWls5Y77owZQmfg==,type:str]
    ADAPTY_SECRET_KEY: ENC[AES256_GCM,data:kG/Sq6SY/UeDtEsoE3d0Ta+n72nRiEOvUYNPu1WCXDuxCrICw4pzlySnC5dOz9IwZWV5Mi0=,iv:VgCj82UrM6A/llN6+nUF0opyWPKt1vszAbkAK9aUDcs=,tag:aecBFovNM8u7DhlA7t2Hzg==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:nhMcRivrAX6MKJ0QjY7L1TGzreT2chXh,iv:9zHVryhbAsxdx/vwNnsRatk0LOptkywrAcVzobYI62s=,tag:ckxxWFPyFPIZv1SqLAFIKg==,type:str]
    PUSHER_APP_KEY: ENC[AES256_GCM,data:mZ4T5di7sjsEGnNLWjXS/hgoTi2xhpu/NpFuLUSqfGeKoWXa3Du4QA==,iv:ZjsRVxsC9VkAc1JMhTBuZGnBFOz5+d4SUodKu7ZugHU=,tag:eOBxkomde3HYbAjWKkkR4g==,type:str]
    PUSHER_APP_SECRET: ENC[AES256_GCM,data:FMg65HdC1BwibL4ypUxRNILeFfL1DZ5JRZuT/fLg2r+Eru/WAlSYVg==,iv:3CrAYNUUx2zJRgWzI45juWwz/WHGEXAXHvbJ321QuuQ=,tag:7xRELFl95183X8v/aH2XIg==,type:str]
    MIX_PUSHER_APP_KEY: ENC[AES256_GCM,data:bq2YjWFGxSgT5cDBtn5oWCFPvPYvPSuG13BEYAM6JHWMnOWKVMDn3g==,iv:jDWhqLdleHVBX8cSTXz0ndn1pHDNqmw65fRSUUL3Rgg=,tag:IMXJapu7tx9QGq/y03SqkA==,type:str]
    MIX_PUSHER_APP_CLUSTER: ENC[AES256_GCM,data:jjdMrevuaFgbwUv6fxGKsjQFUFwp1pJG+hpfzMMILKRn0izPcPZm1A==,iv:vux3RhM0wYXhbvbaL02J0RL8ayW6t887DrfFuMgQ8as=,tag:imK0Bum93VT37+relZ1xsQ==,type:str]
    APN_PRIVATE_KEY: ENC[AES256_GCM,data:yiXd13Bo2mPE7MP/P8MiyW9IEHjw+EWkjhUfJ/A9MM2dvrqwFpA19thYtjWhXCojtLlA28orr6te6rQbZlS/iAEDIFoPVj8SsdsaP/wSPVDmuYPgus0HvLRORph2AL3hk+79bp6kfZ4Pbf337LpJudxGoz0qcYXfG6kqi1KK99D4ZnQZxs81utvJdu6jqATK6u4Ae2Z/ZF++6Gobi/p/8D4p1M47ogGBqe9HH0UT49XXHnH8P3jbMQyXKtNf3QREpCExVV9w4DCT70oJALj7whgW6aVMm3QniVNGI77J9PVcBS5RlrZH1Jg7Rt6fOOyzU5VA4lm0ydbp2P9r,iv:Fs4ihAYVLQqA8IAxyO7IoN1LuEMWenFmM+NxUEv9l10=,tag:wR/nJLAzpp6qTmnn7HHsaQ==,type:str]
    FACEBOOK_CLIENT_ID: ENC[AES256_GCM,data:IQiy5JpCen2fVpvU4eSJ,iv:GaHPbT1Oveho2Ui9YLa87pjImrET1rTli2g+1D4YpQM=,tag:z2ic/+poU/2+94ZNviDTTA==,type:str]
    FACEBOOK_CLIENT_SECRET: ENC[AES256_GCM,data:Q1mi2GewtD8ZhLw0fpMHO5ZTfIoMYH8cICClSeKMuEU=,iv:KpqDoxdHj8v+fsEZ9SyfDhGHT30BcLUDuNtkEbR2LAk=,tag:j30lvrqyCmHO0SWSq9WAmA==,type:str]
    APPLE_CLIENT_SECRET: ENC[AES256_GCM,data:GwKsdJAm48IBP1tQHMQu6g1UYppQ8Xm3dGbl+xJM6rLUmMbUEVztI2cQS2/pdX76MpiG+R4fBHJZK4DI4Ius00fMvp0LaWtpvW79pg39QkrTF6EQPMX7pUz6Ezs//JzGFV+LTJ332pRe0UicHmobgV1z0e5G0C99b3ZyKevl2pvT20LvNkrOtpj6RGNBsQvodIaHIHTUQB9c3ybjWOkUR59NMszwIBwznYO724hgv+rSTMO10O0ZlEJ1dFTnBmeKu58Q/X9ZLyjsXPueOEqGgsCDlYgA8EfGHIfWNr2Fn7ww2FL460uw/LT29R06f7xBxEqbbkx036nkwWJrrTSPWWYtJhxbiVg8WSaXY8i4m/A2GUvUJZy/Qvjgi2Vi3JjpXmX1yqRVWqvir9L0mDleP/BdKQbhjge+rSU49ZPvFhiQ5w==,iv:XyJPNvD1sLQaMRZIWbdFj++ATYH4Uf61hTT1Kjeob9I=,tag:LmdGBfOIfIzp/fZYqdHjjw==,type:str]
    APPLE_PRIVATE_KEY: ENC[AES256_GCM,data:3Nshfm6rQopdUf2sk4Q2xTZBvGsTTb7JESeThztjTBsuwk9Ncu7TtKEE29Cmn5GcXc/eqDqOSr+mZiWJUTpAXkOVMAh7LQoz9KQ5Hyh58V0o5YdddVN7nj1ZEUSQgExWy5EM1OUyCUcJCVYqs7b02sA8xaFQwu25kr+7JJhUIBP8P0U5hmKUywqtrNLYdu8uxPLHZaGHc+9ZyRliN4Vgmq3jX9BJiSTF5ntryzEKgEBYyraCha8YE2Hgwh1gfOPZzeeRscwVl7Kz/ZH0T9KZm2oKIYhKQT7cLwD7cnKpCWOGvBtUvgIsStGlUKsrT6MI/XLGWW/dCQTlWB2w,iv:+Bu290fN89Mw5I0OKqybg+QyY0j3xGyhW3ligd4Fbi0=,tag:4EBO1D23v7cQT06bup+Y2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-21T13:17:16Z"
    mac: ENC[AES256_GCM,data:iDDRIBobHVrGZMknjRZ9GNOTHhGAjQxIDxGpmqPIh/DaU4fHWKRkN5U5VxjeThBeo9iettBHq5kBVjwiCROnXug5pXrNC38OpRXHhTf3idC4haCz9dO+dwxvOReb1FeTzwld5VUUpLHVvjsb5+umg+Sr2RtLKZAoaoFh/WgCPc8=,iv:3zu6+f799xmcqI55nr7juJE12ypyUw7Wj8oQXSaR8cY=,tag:8aiIU0q9M5WEEfIk0ZXF0A==,type:str]
    pgp:
        - created_at: "2022-07-21T13:17:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA94riJsaU78cARAArjdkq733xmqKBaFukLiCuIzeZiwpApkN1OJSecvwJ6cU
            pCbPyXTKyKGfIVoPAsfp5Rj6/FUziUzOVcaXJu7UX9TcKDrbdCg33RWUkhnekKHv
            5hio0Y/8Wjea0iyQHZeK8KZ1I4oKGsy5lhlc01WzgCRLQHft6kXNcf2tmOabcoOC
            b9EDpyfFzuizg3Go2p+JEOx6XSBwbFglryPoA9ST3WGXSbuel5iwZsTSLTg1IDVb
            rdqtMYJoliwfEe8W0kvWcEWDsvjtVc5nQpv1Nh7r9x4XifoWLSXL5hazYz9+1n6x
            il07nnjW5C/ZAwNOJFdefeg3b+EFN9wps+CSNjpBxSVlqGSzp0q+1YrKHdEBd0SP
            +M72Cx1GbYnu7FswUIZjZOrx2giK4BxpKOM/eI2PxNQeRmHMKtvMnOGitasVRckn
            /lfW7F9daaaXKPQwSIeAOxenjCgAlLcZfh3l3izcZJMmaD6xync8s2Xpz15nMyd4
            muxXQd9snhCtP0u3WWdEeIbH2LWAERCV0hG2GPSpNEWvZQxoMvSVvTslYzjIrYTo
            IMGU7Dv/Klteok9kRziKOZ2FHJsGnpDsjZlRkEfXgX+KFuyw8JMLctxqe4MqhoJe
            g3gOMqoYWLzW6SMti8w5IP01cyaYB9CGMMp7piWzu5Zhc6E5USUi/jjzdgmnwn7U
            aAEJAhDRDHEPJOC7t8d3Fw0dZpAzyBf6Bb2JlfjXmLkY8D9yot5y3X3D0Xcry5Jm
            qIMOQo0VJmco2FOMQPiOTf8qR+gpkGQIcnhmxsXqGHTwV0YBPzVw5s8k4lTbXyp0
            zFh5LenIvR5I
            =ZBUD
            -----END PGP MESSAGE-----
          fp: B42C06716985941889E9BE3C3E7A0C9545A09F8C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
