---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  values:
    buckets:
      - name: pgbackrest
        policy: none
        purge: false

    ingress:
      hosts:
        - s3.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
      tls:
        - hosts:
            - s3.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
          secretName: s3.${SECRET_RFSPAGER_CLUSTER_DOMAIN}

    consoleIngress:
      hosts:
        - minio.${SECRET_RFSPAGER_CLUSTER_DOMAIN}

      tls:
        - hosts:
            - s3.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
          secretName: s3.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
