---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ws
  namespace: soketi
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.soketi.app
      chart: soketi
      version: v0.16.2
      sourceRef:
        kind: HelmRepository
        name: soketi-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      hosts:
        - host: es.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
          paths:
            - /

      tls:
        - secretName: soketi.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
          hosts:
            - es.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
