---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ws
  namespace: soketi
spec:
  values:
    ingress:
      hosts:
        - host: es.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
          paths:
            - /

      tls:
        - secretName: soketi.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
          hosts:
            - es.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
