---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      version: "35.x"
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      adminPassword: ${SECRET_GLOBAL_GRAFANA_PASSWORD}
      ingress:
        enabled: true
        path: "/"
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hosts:
          - grafana.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
        tls:
          - secretName: grafana.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
            hosts:
              - grafana.${SECRET_RFSPAGER_CLUSTER_DOMAIN}
    alertmanager:
      enabled: false

    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: default
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorNamespaceSelector: { }
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
