---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      podAnnotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '10254'

      replicaCount: 5
      service:
        type: LoadBalancer
        #externalTrafficPolicy: Local

        annotations:
          metallb.universe.tf/allow-shared-ip: shared-
          metallb.universe.tf/address-pool: default

      publishService:
        enabled: true

      config:
        worker-connections: '100000'
        worker-cpu-affinity: auto 111111111111111111111111
        worker-processes: '16'
        worker-rlimit-nofile: '102400'
        enable-real-ip: true
        forwarded-for-header: proxy_protocol
        ssl-protocols: "TLSv1.3 TLSv1.2"
        custom-http-errors: 404,403,500,503
        enable-vts-status: "false"
        hsts-max-age: "31449600"
        proxy-body-size: "50m"

      resources:
        requests: {}
          #memory: 2048Mi
          #cpu: 16000m

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: "kube-prometheus-stack"

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - ingress-nginx
                topologyKey: kubernetes.io/hostname

    defaultBackend:
      enabled: true

      image:
        repository: ghcr.io/181192/custom-error-pages
        tag: latest

      resources:
        requests:
          memory: 250Mi
          cpu: 25m
