---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: charts
    - name: config
    - name: global
    - name: infra
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/rfspager
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute: { }
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: global-cluster-config
      - kind: Secret
        name: cluster-secrets
      - kind: Secret
        name: global-cluster-secrets