---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./config/rfspager
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
